### ISSUE TITLE
Use the Cfn OIDC provider, not the L3 Construct that wraps a Custom Resource

### ISSUE THREAD

**Issue by douglasnaphas** [VerticalRelevance/aws-github-oidc#2]
Use https://docs.aws.amazon.com/cdk/api/v2/docs/aws-cdk-lib.aws_iam.CfnOIDCProvider.html instead of the current https://www.npmjs.com/package/aws-cdk-github-oidc.

**Comment by douglasnaphas** [comment]
Or not. The [construct](https://github.com/aripalo/aws-cdk-github-oidc) has some value-added services.

**Comment by douglasnaphas** [comment]
The best way will be for the Stack containing the GitHubOIDC Provider to be deployed via the CLI, not through an Action, because of [this](https://github.com/VerticalRelevance/aws-github-oidc/commit/274bbb4b9fff140b7f7a166c97c8ebba6c2fea60) (`::add-mask::` [still logs values](https://github.com/actions/runner/issues/475) if they come from an Action input).

**Comment by douglasnaphas** [comment]
# TODO
- [x] npm deploy script for the OIDC Stack
- [ ] Test whether the announcement referenced [here](https://github.com/aripalo/aws-cdk-github-oidc/issues/24#issuecomment-1632365878) and [here](https://github.com/douglasnaphas/just-a-table/issues/1#issuecomment-1627541606) means that I can put `anything` as the thumbprint, and authentication to GitHub will still work.
- [ ] Are [these](https://github.com/aripalo/aws-cdk-github-oidc/blob/ce198f263ad0b3417faa75bb84a7ee2d322e9073/src/provider.ts#L22-L23) the right thumbprints? Are they a from a high-enough level CA, as per [this discussion](https://github.com/aws/aws-cdk/issues/21197#issuecomment-1596158662)?

**Comment by douglasnaphas** [comment]
> The best way will be for the Stack containing the GitHubOIDC Provider to be deployed via the CLI, not through an Action, because of [this](https://github.com/VerticalRelevance/aws-github-oidc/commit/274bbb4b9fff140b7f7a166c97c8ebba6c2fea60) (`::add-mask::` [still logs values](https://github.com/actions/runner/issues/475) if they come from an Action input).

Or maybe I can add a manual approval step. The point is to not leave creds in GitHub Actions Secrets for any period of time, even if they're temp creds.

Actually, this will never work. It has to be a manual run, locally. There's no other way to protect creds from someone who is admin over the org where the repo lives.

**Comment by douglasnaphas** [comment]
A Provider created (I think) from running this repo locally.

```
[cloudshell-user@ip-10-6-69-76 ~]$ aws iam list-open-id-connect-providers                                                                                                                                                                                             
{
    "OpenIDConnectProviderList": [
        {
            "Arn": "arn:aws:iam::287213416300:oidc-provider/token.actions.githubusercontent.com"
        }
    ]
}
[cloudshell-user@ip-10-6-69-76 ~]$ aws iam get-open-id-connect-provider

usage: aws [options] <command> <subcommand> [<subcommand> ...] [parameters]
To see help text, you can run:

  aws help
  aws <command> help
  aws <command> <subcommand> help

aws: error: the following arguments are required: --open-id-connect-provider-arn

[cloudshell-user@ip-10-6-69-76 ~]$ aws iam get-open-id-connect-provider --open-id-connect-provider-arn arn:aws:iam::287213416300:oidc-provider/token.actions.githubusercontent.com
{
    "Url": "token.actions.githubusercontent.com",
    "ClientIDList": [
        "sts.amazonaws.com"
    ],
    "ThumbprintList": [
        "6938fd4d98bab03faadb97b34396831e3780aea1",
        "a031c46782e6e6c662c2c87c76da9aa62ccabd8e"
    ],
    "CreateDate": "2023-05-26T11:14:53.871000+00:00",
    "Tags": []
}
```

**Comment by douglasnaphas** [comment]
Maybe the right workflow is:
1. Once per account, from the CLI, deploy a Provider stack from this repo.
2. In each repo, include in your app a Role Stack, containing the deployment role. This repo should export a Construct to use as the single Construct in that Role Stack.
3. Once per repo (or app), from the CLI, deploy a Role Stack for that app.
4. In the app repo, set up CI to use [aws-actions/configure-aws-credentials](https://github.com/aws-actions/configure-aws-credentials) based on [these docs](https://docs.github.com/en/actions/deployment/security-hardening-your-deployments/configuring-openid-connect-in-amazon-web-services#adding-the-identity-provider-to-aws).

**Comment by douglasnaphas** [comment]
The `provider-cfn` directory's stack currently deploys _not_ a Cfn Provider, but rather IAM's Construct, which is implemented using a custom resource. The directory name is misleading.
